- name: Are Settings Installed
  command: test -d /home/vagrant/.habitat
  register: settings_installed_check
  ignore_errors: yes
  changed_when: False

- name: Install Settings
  git: repo=https://github.com/BrandonOCasey/habitat-my-settings dest=/home/vagrant/.habitat update=no
  when: settings_installed_check.rc != 0

- name: Install Settings to bash_profile
  shell: echo '. /home/vagrant/.habitat/habitat' >> /home/vagrant/.bash_profile
  when: settings_installed_check.rc != 0

- name: Install Setting Plugins
  shell: . /home/vagrant/.habitat/habitat install
  when: settings_installed_check.rc != 0

